### ISSUE TITLE
求求大神指教菜鸟

### ISSUE THREAD

**Issue by JinhaoTANGCQ** [jemmyzheng/report-server#1]
大神能不能分享一下创建数据库的sql文件，或者cdm/pdm，我是一个在校生想学习一下大神的思路，只看mapper头好痛思路还是理不清，关于C端Ant-Design-Pro一知半解，不能将网页部分直接整合到springboot里吗？

**Comment by jemmyzheng** [comment]
你要的SQL已经放在项目根目录了，客户端没整合，是因为我一开始就按着前后端分离的方式来构建项目的
